server:
  transport:
    http:
      enabled: true
      address: 0.0.0.0:8081
    sse:
      enabled: false
      address: 0.0.0.0:8080
      #baseURL: http://host.docker.internal:8080
      baseURL: http://0.0.0.0:8080
    stdio:
      enabled: false

  tools:
    # List of tools to disable if you don't want to serve them to the client/host.
    disabled: []

  chronosphere:
    apiURL: https://${CHRONOSPHERE_ORG_NAME:""}.chronosphere.io
    # The API token for Chronosphere, used to authenticate requests.
    # Leave empty if forwarding bearer token.
    apiToken: ${CHRONOSPHERE_API_TOKEN:""}

instrument:
  logs:
    level: ${LOG_LEVEL:info}
    outputPaths:
      - stderr
    errorOutputPaths:
      - stderr
